// Internal owner dashboard. Never indexed, never server-rendered for SEO.
// https://nuxt.com/docs/api/configuration/nuxt-config
import { fileURLToPath } from "node:url";

// `npm run build:check` (LOKL_BUILD_CHECK=1) builds into its own folders, so
// a build check never touches the .nuxt, .output or Vite cache that a running
// dev server uses (a plain `nuxt build` in the app folder can break it).
const buildCheck = process.env.LOKL_BUILD_CHECK === "1";
const buildCheckFolders = buildCheck
  ? { buildDir: ".nuxt-check", nitro: { output: { dir: ".output-check" } }, vite: { cacheDir: "node_modules/.cache/vite-check" } }
  : {};

export default defineNuxtConfig({
  ...buildCheckFolders,
  // Shared UI layer: ui-thing components, theme, Tailwind (docs/frontend.md).
  extends: ["@repo/ui"],

  compatibilityDate: "2025-07-15",

  runtimeConfig: {
    // AI drafts of guides (server only, never NUXT_PUBLIC_): NUXT_ANTHROPIC_API_KEY,
    // and NUXT_ANTHROPIC_MODEL to change the model (settled: Opus).
    anthropicApiKey: "",
    anthropicModel: "claude-opus-5-5",
    public: {
      // NUXT_PUBLIC_WEBSITE_URL: where the website's /api/admin/* routes are.
      // Refunds and anything else that needs Stripe go through them, with
      // the admin's own sign-in token (decision 14).
      websiteUrl: "http://localhost:3100",
    },
  },
  devtools: { enabled: true },

  // Admin is an authenticated tool, so SSR adds nothing but complexity.
  ssr: false,

  // Fixed port, clear of The Reserve (3000, falling back to 3001).
  devServer: {
    port: 3101,
  },

  app: {
    head: {
      title: "Admin",
      meta: [{ name: "robots", content: "noindex, nofollow" }],
    },
  },

  modules: ["@nuxt/eslint", "@nuxtjs/supabase"],

  supabase: {
    // The server key is read only at runtime (NUXT_SUPABASE_SECRET_KEY). The
    // module's own defaults read it from the environment while building,
    // which baked the hosted project's key into the server output (found
    // 2026-10-09); these literal empty values replace those defaults, and the
    // build check (npm run build:secrets-check) fails if one comes back.
    secretKey: "",
    serviceKey: "",
    // Auth cookies. The module's default forces Secure, which Safari refuses on
    // http://localhost (Chrome allows it), so the sign-in link's one-time code
    // verifier was never saved and every Safari sign-in failed. Secure in
    // production builds only; development runs on plain http. SameSite stays
    // "lax": arriving from the emailed link is a top-level visit, which lax
    // allows. Override at runtime with NUXT_PUBLIC_SUPABASE_COOKIE_OPTIONS_SECURE.
    cookieOptions: {
      maxAge: 60 * 60 * 8,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
    },
    // Generated by `npm run db:types` from the linked project; every query
    // is typed against the real schema. An absolute path: the module resolves
    // relative paths and aliases from its own folder.
    types: fileURLToPath(new URL("../../packages/types/src/database.ts", import.meta.url)),
    redirectOptions: {
      login: "/login",
      callback: "/confirm",
      exclude: [],
      saveRedirectToCookie: true,
    },
  },
});
