// https://nuxt.com/docs/api/configuration/nuxt-config
import { fileURLToPath } from "node:url";

// `npm run build:check` (LOKL_BUILD_CHECK=1) builds into its own folders, so
// a build check never touches the .nuxt, .output or Vite cache that a running
// dev server uses (a plain `nuxt build` in the app folder can break it).
const buildCheck = process.env.LOKL_BUILD_CHECK === "1";
const buildCheckFolders = buildCheck
  ? { buildDir: ".nuxt-check", nitro: { output: { dir: ".output-check" } }, vite: { cacheDir: "node_modules/.cache/vite-check" } }
  : {};

export default defineNuxtConfig({
  ...buildCheckFolders,
  // Shared UI layer: ui-thing components, theme, Tailwind (docs/frontend.md).
  extends: ["@repo/ui"],

  compatibilityDate: "2025-07-15",
  devtools: { enabled: true },

  css: ["lenis/dist/lenis.css"],

  nuxtZod: {
    zodVersion: "v4",
  },

  // Fixed port, clear of The Reserve (3000, falling back to 3001).
  devServer: {
    port: 3100,
  },

  runtimeConfig: {
    // Server only. Set via NUXT_STRIPE_SECRET_KEY / NUXT_STRIPE_WEBHOOK_SECRET
    // (connected-account events) / NUXT_STRIPE_PAYMENTS_WEBHOOK_SECRET (booking
    // payments, events on lokl's own account).
    stripeSecretKey: "",
    stripeWebhookSecret: "",
    stripePaymentsWebhookSecret: "",
    // NUXT_JOB_SECRET: the timed jobs' shared secret (/api/jobs/*). Empty
    // means the job routes refuse every call.
    jobSecret: "",
    // Booking emails (server/utils/bookingEmails.ts), all server only:
    // NUXT_RESEND_API_KEY (its own Resend key, not the one Supabase uses for
    // sign-in emails), NUXT_EMAIL_MODE (off | allowlist | send),
    // NUXT_EMAIL_ALLOWLIST (comma-separated, for allowlist mode),
    // NUXT_EMAIL_REPLY_TO (required to send), NUXT_EMAIL_FROM.
    // NUXT_ADMIN_ORIGIN: the admin app's exact address, the only origin
    // allowed to call /api/admin/* (decision 14). Empty refuses every call.
    adminOrigin: "",
    resendApiKey: "",
    emailMode: "off",
    emailAllowlist: "",
    emailReplyTo: "",
    emailFrom: "lokl <lokl@innatetheory.com>",
    public: {
      // NUXT_PUBLIC_STRIPE_KEY / NUXT_PUBLIC_SITE_URL
      stripeKey: "",
      siteUrl: "http://localhost:3100",
      // NUXT_PUBLIC_SUPPORT_EMAIL: where providers and customers can write
      // to lokl (the same address booking emails reply to, for now).
      supportEmail: "",
    },
  },

  // @nuxtjs/seo: fills the "%siteName" in page titles ("Sign in | lokl").
  // The site URL comes from NUXT_PUBLIC_SITE_URL.
  site: {
    name: "lokl",
  },

  // Sitemap: the public pages, from a server route that reads as a signed-out
  // visitor. Signed-in and sign-in pages stay out.
  sitemap: {
    sources: ["/api/__sitemap__/urls"],
    exclude: ["/dashboard/**", "/login", "/confirm"],
  },

  supabase: {
    // Auth cookies. The module's default forces Secure, which Safari refuses on
    // http://localhost (Chrome allows it), so the sign-in link's one-time code
    // verifier was never saved and every Safari sign-in failed. Secure in
    // production builds only; development runs on plain http. SameSite stays
    // "lax": arriving from the emailed link is a top-level visit, which lax
    // allows. Override at runtime with NUXT_PUBLIC_SUPABASE_COOKIE_OPTIONS_SECURE.
    cookieOptions: {
      maxAge: 60 * 60 * 8,
      sameSite: "lax",
      secure: process.env.NODE_ENV === "production",
    },
    // Generated by `npm run db:types` from the linked project; every query
    // is typed against the real schema. An absolute path: the module resolves
    // relative paths and aliases from its own folder.
    types: fileURLToPath(new URL("../../packages/types/src/database.ts", import.meta.url)),
    // Public pages stay open; the provider dashboard and the customer's
    // account pages require sign-in.
    redirectOptions: {
      login: "/login",
      callback: "/confirm",
      // Providers' dashboard, and customers' own bookings.
      include: ["/dashboard*", "/account*"],
      saveRedirectToCookie: true,
    },
  },

  routeRules: {
    // Public data (docs/design/browse-and-listing-pages.md, Caching). Browse
    // and market data refresh within a minute; a listing's own data isn't
    // cached, so a listing taken down disappears from its page at once.
    // Temporary (302) while Atlanta is the only market; a market picker
    // replaces them when there's a second (docs/design/browse-and-listing-pages.md).
    // Exact paths only: /experiences/<slug> listing pages aren't redirected.
    "/experiences": { redirect: { to: "/atlanta/experiences", statusCode: 302 } },
    "/services": { redirect: { to: "/atlanta/services", statusCode: 302 } },
    //
    // Cached for 60 seconds, without serving stale copies (swr: false). With
    // stale-while-revalidate, a page whose fresh answer had become a 404 (a
    // guide unpublished, a category or market switched off) kept serving its
    // old copy indefinitely, because errors aren't cached and so never replace
    // it (found 2026-10-03). Now, once a copy is a minute old, the next
    // request waits for a fresh answer, 404s included.
    "/api/public/browse": { cache: { maxAge: 60, swr: false } },
    "/api/public/markets/**": { cache: { maxAge: 60, swr: false } },
    // Guides (docs/design/destination-guides.md, Caching): a publish or
    // unpublish in the admin app shows on the site within a minute.
    "/api/public/guides/**": { cache: { maxAge: 60, swr: false } },
    "/api/public/homepage-guides": { cache: { maxAge: 60, swr: false } },
    "/dashboard/**": { robots: false },
    "/account/**": { robots: false },
    "/login": { robots: false },
    "/confirm": { robots: false },
  },

  modules: [
    "@nuxt/eslint",
    "@nuxt/scripts",
    "@nuxt/test-utils",
    // '@nuxtjs/sanity',
    "@nuxtjs/seo",
    "@nuxtjs/supabase",
    "dayjs-nuxt",
    "lenis/nuxt",
    "nuxt-gtag",
    "nuxt-locomotive-scroll",
    "nuxt-swiper",
    "nuxt-zod",
  ],
});
